In [10]:
import numpy as np
import pandas as pd

city_list = ["Uldah", "Gridania", "Pandora", "Reach", "Queensdale"]
color_list = ["red", "blue", "green", "yellow", "purple", "orange"]
gender_list = ["male","female"]
reading_list = ["level 1", "level 2", "level 3", "level 4"]
hobby_list = ["soccer", "swimming", "dancing", "scouts", "gymnastics"]
language_list = ["German", "Dutch", "American", "Turkish", "Japanese"]
introverted_list = ["yes", "no"]
siblings_list = ["no", "1", "2", "3", "4"]

random_df = pd.DataFrame()
length = 10000
random_df["city"] = np.random.choice(city_list, length)
random_df["color"] = np.random.choice(color_list, length)
random_df["gender"] = np.random.choice(gender_list, length)
random_df["reading"] = np.random.choice(reading_list, length)
random_df["hobby"] = np.random.choice(hobby_list, length)
random_df["language"] = np.random.choice(language_list, length)
random_df["introverted"] = np.random.choice(introverted_list, length)
random_df["siblings"] = np.random.choice(siblings_list, length)
random_df

,city,color,gender,reading,hobby,language,introverted,siblings
0,Reach,orange,female,level 1,soccer,Turkish,no,3
1,Gridania,blue,male,level 2,soccer,Turkish,no,2
2,Reach,blue,female,level 4,swimming,Turkish,no,4
3,Queensdale,green,female,level 1,swimming,American,yes,1
4,Pandora,yellow,male,level 3,dancing,German,yes,3
...,...,...,...,...,...,...,...,...
9995,Uldah,orange,male,level 1,swimming,American,no,2
9996,Queensdale,yellow,male,level 3,soccer,Dutch,yes,4
9997,Queensdale,orange,female,level 2,swimming,Dutch,yes,no
9998,Reach,red,male,level 3,gymnastics,Japanese,yes,2
9999,Pandora,orange,male,level 3,swimming,Dutch,no,2